apiVersion: v1
kind: Pod
metadata:
  name: app1-pod
  namespace: gw-poc-ns
  labels:
    app: app1
spec:
  containers:
    - name: nginx
      image: nginx:latest # you can use your app image here, for poc i have used nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: app2-pod
  namespace: gw-poc-ns
  labels:
    app: app2
spec:
  containers:
    - name: nginx
      image: nginx:latest # you can use your app image here, for poc i have used nginx
      ports:
        - containerPort: 80
