apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: app1-route
  namespace: gw-poc-ns
spec:
  parentRefs:
    - name: saquib-gw
  hostnames:
    - app1.internal  # this hostname can be anything
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: app1-svc
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: app2-route
  namespace: gw-poc-ns
spec:
  parentRefs:
    - name: saquib-gw
  hostnames:
    - app2.internal
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: app2-svc
          port: 80
